### ISSUE TITLE
building on Ubuntu 14.04 isn't working (libgit2 error)

### ISSUE THREAD

**Issue by superjan** [ark-lang/arkade#102]
When I try to build arkade on my laptop running Ubuntu 14.04 32-bit, I get errors like:
```
home/jan/Repositories/arkade/src/actions/init_action.c:50: undefined reference to `git_libgit2_init'
```
Also: ``git_libgit2_shutdown``

How can I fix this? Installed libgit2 using ``sudo apt-get install libgit2-0 libgit2-dev``.

**Comment by felixangell** [comment]
Looks like it's not linking correctly, try building libgit from the source and installing it like that instead of via apt

**Comment by superjan** [comment]
Installed libgit2 to ``/usr/local`` what I get now is ``No rule to make target  '/usr/lib/i386-linux-gnu/libgit2.so' needed by 'bin/arkade'.`` Installed libgit2 like described in the README on their repo.

**Comment by felixangell** [comment]
Have you regenerated the makefiles? `cmake .`

**Comment by superjan** [comment]
Ok basically libgit2 is now working, but I now get that ``-Wno-sometimes-uninitialized`` is an unrecognized command.

**Comment by felixangell** [comment]
@superjan Are you using clang or gcc?

**Comment by superjan** [comment]
@felixangell Installed are booth.

**Comment by superjan** [comment]
Removed clang, now its working.

**Comment by felixangell** [comment]
haha ok
