### ISSUE TITLE
parse toml config files, verify them and also allow easy loading of rules

### ISSUE THREAD

**Issue by felixangell** [ark-lang/arkade#2]
Again, probably a few libraries for this, but I'd probably roll my own parser, I'm not sure. Should also be able to load values from the config files pretty trivially, and the config file should be verified -- perhaps even verify the dependencies exist?

**Comment by SamTebbs33** [comment]
Judging by the spec (https://github.com/toml-lang/toml), it doesn't seem like it would be to difficult to parse, there are however libraries out there (e.g. https://github.com/toml-lang/toml) that seem decent.

**Comment by felixangell** [comment]
@SamTebbs33 Yeah, I've seen a few libraries; but I may roll my own because it's easier for when we write this thing in Ark. Also, it'd be a bit of fun to get one working and as you said, it looks pretty easy to parse.

**Comment by SamTebbs33** [comment]
I agree that it would in fact be better to write it in Ark, since it would essentially be a good opportunity to test the language and come up with new ideas!

**Comment by felixangell** [comment]
Yep! This is my first dog-fooding project for Ark, but for now it's in C till Ark works well enough :)
