### ISSUE TITLE
License key/value for config

### ISSUE THREAD

**Issue by felixangell** [ark-lang/arkade#22]
The GitHub API allows you to load a license if you post. For instance, `mit` it will generate a `mit` license in the repository. Perhaps it should pull after this to avoid fast forwards? Also, the licensed would have to be validated so you can't just put in `license = "asdadfasdfsdwer123"`.

**Comment by vnev** [comment]
I've implemented this, but Github doesn't seem to be generating the license file. The JSON looks intact so I need to look into why this is happening.

**Comment by felixangell** [comment]
Gotta close it peasant
