### ISSUE TITLE
Move github username to arkade config rather than project config

### ISSUE THREAD

**Issue by felixangell** [ark-lang/arkade#34]
```toml
[config]
# some settings here?

[config.github]
username = "felixangell"
token = "abcdefabcdefabcdefabcdef"
```

**Comment by MovingtoMars** [comment]
You should make it so that you can set the default in the arkade config, but optionally override it in the project config.

**Comment by felixangell** [comment]
Perhaps, but a username needs a token so it can auth with github, so that would have to be specified too, and that's not an ideal thing for the project toml? Although the project toml is gitignored from the repository, doesn't sound like a great idea imo
