### ISSUE TITLE
add website to configuration file

### ISSUE THREAD

**Issue by felixangell** [ark-lang/arkade#38]
i.e. doing

```
website = "http://www.google.com"
```

will set the github repo website to google. Note that website URL's should probably be validated.

**Comment by MovingtoMars** [comment]
Make it explicit.

eg:
```
github-host = "http://www.google.com"
```

**Comment by felixangell** [comment]
I'll do:

[config]
#project specific

[config.github]
website = "whatever"
# etc

**Comment by MovingtoMars** [comment]
@felixangell +1
