### ISSUE TITLE
popen() is unsafe

### ISSUE THREAD

**Issue by MovingtoMars** [ark-lang/arkade#40]
`popen()` is still unsafe.

You can do things like this:

```
sachiel@jiyuu:[testing]$ touch '; rm -rf ~'
sachiel@jiyuu:[testing]$ ls
; rm -rf ~
sachiel@jiyuu:[testing]$ 
```

Arkade doesn't sanitize its input. Guess what happens when you run a command involving that file with `popen()`.

**Comment by felixangell** [comment]
Cheers

**Comment by vnev** [comment]
We'll be using `libgit` to handle a lot of the git commands so the `exec_process` function (which in turn uses `popen`) will not be needed.

**Comment by felixangell** [comment]
Leave it open till it's actually fully fixed though

**Comment by vnev** [comment]
Oh right. Apologies

**Comment by felixangell** [comment]
This will still be used for the build command though, so we still have to sanitise everything.
