### ISSUE TITLE
Pre-build and post-build commands in the package's toml file

### ISSUE THREAD

**Issue by SamTebbs33** [ark-lang/arkade#78]
A useful addition to the package's toml file would be `pre-build`and `post-build` command/s that would be run before and after the build, respectively These could be used for making batched changes to files before and/or after a build has taken place.

```
pre-build = [ "echo Pre-build command #1", "echo Pre-build command #2" ]
post-build = [ "echo Post-build command #1", "echo Post-build command #2" ]
```
I think that these would supplement the existing ```build``` command nicely.

**Comment by MovingtoMars** [comment]
I like it.

**Comment by raoulvdberge** [comment]
:+1: maybe those should be a list, to support multiple comments in a clean way:

**Comment by SamTebbs33** [comment]
@raoulvdberge That's a good idea, I'll edit the OP!

**Comment by felixangell** [comment]
Cool, I'll consider this approved :) Wont close till implemented.
