### ISSUE TITLE
CMake errors with libgit2 on Arch Linux

### ISSUE THREAD

**Issue by vnev** [ark-lang/arkade#79]
There seems to be a problem with CMake initializing `CMAKE_MODULE_PATH` upon running `cmake .` inside the `arkade` dir. It's not able to accurately locate `FindLibGit2.cmake`. Not sure if this is an isolated issue. I don't have an accurate error log but I'm certain this is what caused it.
Might want to look into this however.

@MovingtoMars can you test it on your Arch install and see if it gives a similar message?

**Comment by felixangell** [comment]
This is most likely because you're on Cmake 2.8?

**Comment by vnev** [comment]
Can't check anymore :/

Maybe Liam can check both to see which works? If its alright with him

**Comment by raoulvdberge** [comment]
why is the cmake file so complicated? shouldn't something like <code>target_link_libraries(arkade curl libgit2)</code> just work?

**Comment by felixangell** [comment]
I dunno, would it?

**Comment by raoulvdberge** [comment]
oh, you're using modules. I dunno, just specifying the lib should work?

**Comment by felixangell** [comment]
I dunno, well it works as it does now - I'm just pretty certain a lot of linux based systems default to cmake 2.8, which doesn't seem to work with the build

**Comment by MovingtoMars** [comment]
```
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindLibgit2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Libgit2", but
  CMake did not find one.

  Could not find a package configuration file provided by "Libgit2" with any
  of the following names:

    Libgit2Config.cmake
    libgit2-config.cmake

  Add the installation prefix of "Libgit2" to CMAKE_PREFIX_PATH or set
  "Libgit2_DIR" to a directory containing one of the above files.  If
  "Libgit2" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/sachiel/Documents/Development/github/arkade/CMakeFiles/CMakeOutput.log".

```

**Comment by vnev** [comment]
^ exact same error

**Comment by naegelejd** [comment]
Hey did you guys fix this yet? If not, do these two changes help?
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b55ba78..543a022 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -2,11 +2,11 @@ cmake_minimum_required(VERSION 3.0)
 
 project(arkade C)
 
-set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_SOURCE_DIR}/CMake/Modules")
+list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/CMake/Modules")
 set(CMAKE_C_FLAGS "-Wall -Wextra -g -Wno-sometimes-uninitialized -Wno-unused-parameter -pedantic -Wno-unused-parameter -std=c99")
 set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "bin/")
 
-find_package(Libgit2 REQUIRED)
+find_package(LibGit2 REQUIRED)
 set(LIBS ${LIBS} ${LIBGIT2_LIBRARIES})
 include_directories(${LIBGIT2_INCLUDE_DIR} ${CMAKE_SOURCE_DIR}/include ${CMAKE_SOURCE_DIR}/include/toml)
 file(GLOB SOURCES ${CMAKE_SOURCE_DIR}/src/*.c ${CMAKE_SOURCE_DIR}/src/toml/*.c ${CMAKE_SOURCE_DIR}/src/actions/*.c)
```

**Comment by felixangell** [comment]
@naegelejd I'll give it a try later today, I'll have to install Arch Linux on Virtual Box though :disappointed:

**Comment by MovingtoMars** [comment]
@naegelejd This gets it working on my box. Sweet.

**Comment by MovingtoMars** [comment]
Closed by fcedffe1b1ca7969fec7541b72eace58ea17abda

**Comment by felixangell** [comment]
Nice :+1: Thank you based @naegelejd

**Comment by vnev** [comment]
Ty @naegelejd
